version: 0.0
os: linux
files:
  - source: /
    destination: /django/new_chatapp
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1000
      runas: root
  AfterInstall:
    - location: scripts/change_File.sh
      timeout: 1000
      runas: root
  ApplicationStart:
    - location: /scripts/start.sh
      timeout: 1000
      runas: root
  ApplicationStop:
    - location: /scripts/stop_server.sh
      timeout: 1000
      runas: root
